---
version: 2
linters:
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/gorilla/websocket.Conn).WriteJSON
        - (net/http.ResponseWriter).Write
formatters:
  enable:
    - gofmt
